# NumPy Practice Notebook

This notebook demonstrates NumPy arrays, array operations,
indexing, slicing, reshaping, masking, broadcasting,
and common aggregate functions.

In [31]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## 1. Creating a 1D Array

In [32]:
arr_1d = np.array([10, 20, 30, 40, 50])

print("Array:", arr_1d)
print("Number of dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)
print("Data type:", arr_1d.dtype)

Array: [10 20 30 40 50]
Number of dimensions: 1
Shape: (5,)
Data type: int64


In [33]:
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])
print("First three elements:", arr_1d[:3])
print("Elements from index 2:", arr_1d[2:])

First element: 10
Last element: 50
First three elements: [10 20 30]
Elements from index 2: [30 40 50]


## 2. Creating a 2D Array

In [34]:
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(arr_2d)

print("\nNumber of dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data type:", arr_2d.dtype)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Number of dimensions: 2
Shape: (3, 3)
Data type: int64


In [35]:
print("Element at row 1, column 2:", arr_2d[1, 2])

print("\nFirst row:", arr_2d[0, :])

print("\nFirst column:", arr_2d[:, 0])

print("\nFirst two rows:")
print(arr_2d[:2, :])

Element at row 1, column 2: 60

First row: [10 20 30]

First column: [10 40 70]

First two rows:
[[10 20 30]
 [40 50 60]]


## 3. Creating a 3D Array

In [36]:
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(arr_3d)

print("\nNumber of dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)
print("Data type:", arr_3d.dtype)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Number of dimensions: 3
Shape: (2, 2, 3)
Data type: int64


In [37]:
print("First element:", arr_3d[0, 0, 0])

print("Element at [1, 0, 2]:", arr_3d[1, 0, 2])

print("\nFirst block:")
print(arr_3d[0])

First element: 1
Element at [1, 0, 2]: 9

First block:
[[1 2 3]
 [4 5 6]]


## 4. Reshaping Arrays

In [38]:
arr = np.arange(1, 13)

print("Original array:")
print(arr)

reshaped_arr = arr.reshape(3, 4)

print("\nReshaped array:")
print(reshaped_arr)

print("\nOriginal shape:", arr.shape)
print("New shape:", reshaped_arr.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Original shape: (12,)
New shape: (3, 4)


## 5. NumPy Array Creation Functions

In [39]:
zeros_array = np.zeros((2, 3))

print("Zeros array:")
print(zeros_array)

Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
ones_array = np.ones((2, 3))

print("Ones array:")
print(ones_array)

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
range_array = np.arange(0, 10, 2)

print("Array created using arange:")
print(range_array)

Array created using arange:
[0 2 4 6 8]


In [42]:
linear_array = np.linspace(0, 1, 5)

print("Array created using linspace:")
print(linear_array)

Array created using linspace:
[0.   0.25 0.5  0.75 1.  ]


## 6. Mathematical and Vectorized Operations

In [43]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Array A:", a)
print("Array B:", b)

Array A: [10 20 30 40 50]
Array B: [1 2 3 4 5]


In [44]:
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [45]:
print("Square of A:", a ** 2)
print("Square root of A:", np.sqrt(a))
print("A multiplied by 2:", a * 2)

Square of A: [ 100  400  900 1600 2500]
Square root of A: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
A multiplied by 2: [ 20  40  60  80 100]


In [46]:
numbers = np.array([1, 2, 3, 4, 5])

result = numbers * 10

print("Original:", numbers)
print("After multiplying by 10:", result)

Original: [1 2 3 4 5]
After multiplying by 10: [10 20 30 40 50]


## 7. Boolean Masking and Filtering

In [47]:
marks = np.array([45, 72, 88, 34, 91, 65, 78, 29])

print("Marks:", marks)

Marks: [45 72 88 34 91 65 78 29]


In [48]:
marks = np.array([45, 72, 88, 34, 91, 65, 78, 29])

print("Marks:", marks)

Marks: [45 72 88 34 91 65 78 29]


In [49]:
marks = np.array([45, 72, 88, 34, 91, 65, 78, 29])

print("Marks:", marks)

Marks: [45 72 88 34 91 65 78 29]


In [50]:
mask = marks >= 50

print("Boolean mask:", mask)

Boolean mask: [False  True  True False  True  True  True False]


In [51]:
passed_marks = marks[marks >= 50]

print("Marks greater than or equal to 50:", passed_marks)

Marks greater than or equal to 50: [72 88 91 65 78]


In [52]:
passed_marks = marks[marks >= 50]

print("Marks greater than or equal to 50:", passed_marks)

Marks greater than or equal to 50: [72 88 91 65 78]


In [53]:
low_marks = marks[marks < 40]

print("Marks below 40:", low_marks)

Marks below 40: [34 29]


In [54]:
filtered_marks = marks[(marks >= 50) & (marks <= 80)]

print("Marks between 50 and 80:", filtered_marks)

Marks between 50 and 80: [72 65 78]


## 8. Broadcasting

In [55]:
numbers = np.array([10, 20, 30, 40, 50])

result = numbers + 5

print("Original array:", numbers)
print("After adding 5:", result)

Original array: [10 20 30 40 50]
After adding 5: [15 25 35 45 55]


In [56]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

values = np.array([1, 2, 3])

result = matrix + values

print("Original matrix:")
print(matrix)

print("\nValues:", values)

print("\nAfter broadcasting:")
print(result)

Original matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Values: [1 2 3]

After broadcasting:
[[11 22 33]
 [41 52 63]
 [71 82 93]]


## 9. Aggregate Functions

In [57]:
scores = np.array([45, 72, 88, 34, 91, 65, 78, 29])

print("Scores:", scores)

Scores: [45 72 88 34 91 65 78 29]


In [58]:
print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))

Sum: 502
Mean: 62.75
Minimum: 29
Maximum: 91
Median: 68.5


In [59]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:")
print(matrix)

print("\nTotal:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Minimum:", np.min(matrix))
print("Maximum:", np.max(matrix))
print("Median:", np.median(matrix))

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Total: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Median: 50.0


In [60]:
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))

Sum of each column: [120 150 180]
Sum of each row: [ 60 150 240]


## Conclusion

This notebook demonstrates the fundamental features of NumPy, including
array creation, dimensions, indexing, slicing, reshaping, mathematical
operations, vectorization, Boolean masking, broadcasting, and aggregate
functions. These operations provide an efficient way to work with numerical
data in Python.